{
  "name": "Envoy MQTT Proxy",
  "version": "1.0.0",
  "slug": "envoy_mqtt",
  "description": "TCP failover proxy for MQTT using Envoy",
  "arch": ["amd64", "armv7", "aarch64"],
  "startup": "services",
  "boot": "auto",
  "host_network": true,
  "legacy": true,
  "schema": {}
}